### ISSUE TITLE
Zlib did not come to the end of the string  on large files

### ISSUE THREAD

**Issue by ufobat** [benkasminbullock/gzip-faster#7] opened 2017-07-18 15:08 UTC
I've encounering following error

```
perl -MGzip::Faster=gunzip_file -we 'gunzip_file(shift);' 'test.bin.gz'
Zlib did not come to the end of the string - -5 at /opt/perl/lib/site_perl/5.20.3/x86_64-linux/Gzip/Faster.pm line 76.

``` 
in oder to figure out what zlib_status is i applyed follwing chagne:
```
-- a/gzip-faster-perl.c
+++ b/gzip-faster-perl.c
@@ -373,7 +373,7 @@ gunzip_faster (gzip_faster_t * gf)
        croak ("Zlib did not finish processing the string");
     }
     if (zlib_status != Z_STREAM_END) {
-   croak ("Zlib did not come to the end of the string");
+            croak ("Zlib did not come to the end of the string - %d", zlib_status);
     }
     inflateEnd (& gf->strm);
     if (gf->user_object && gf->is_gzip && header.done == 1) {
```

my file is rather big:

$ dd if=/dev/urandom of=test.bin bs=100M count=50
$ gzip test.bin
$ ls -l test.bin.gz
-rw-r--r-- 1 root root 5138896180 18. Jul 16:15 test.bin.gz

i am wondering whether this is a memory issue? according to https://www.zlib.net/manual.html when you ancounter a Z_BUF_ERROR you should create you output buffer. which is not the case in the do while loopl

**Comment by benkasminbullock** [comment] 2017-07-18 20:23
Please can you confirm that you are using version 0.20 of the module. Your line numbers are slightly different from the current ones. Assuming you're not using an old version, I am not really sure what caused the error here, but Gzip::Faster just works on in-memory buffers, so in this case you are trying to store several gigabytes in a single Perl scalar. Z_BUF_ERROR is handled here at the moment:

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L342

That does not end the do while loop.

Gzip::Faster always writes into its own output buffer:

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L337

This is part of the structure itself:

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L31

**Comment by ufobat** [comment] 2017-07-18 20:53
the version i've installed is 
```
perl -MGzip::Faster -E 'say $Gzip::Faster::VERSION'
0.20
```

I've used the current version of this github repo to change the croak() call and recompile it, in oder to figure out what is the value in line https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L376

let me quote https://www.zlib.net/manual.html
> If the parameter flush is set to Z_FINISH, pending input is processed, pending output is flushed and deflate returns with Z_STREAM_END if there was enough output space. If deflate returns with Z_OK or Z_BUF_ERROR, this function must be called again with Z_FINISH and more output space (updated avail_out) but no more input data, until it returns with Z_STREAM_END or an error. After deflate has returned Z_STREAM_END, the only possible operations on the stream are deflateReset or deflateEnd.
> 

I am really not a c programmer nor did i read the whole manual, but i am wondering why can I be sure that
https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L31 or in other words a buffer with the size of CHUNK is *always* large enough? (Because you should do it again with a larger output buffer, right?)

i dont think the scalar size of perl does really matter here, because i could open and store even bigger files in one scalar.

```
[root@xx store]# ll tmp 
-rw-r--r-- 1 root root 6816840186 18. Jul 22:49 tmp

[root@xx store]# ps aux | grep perl
root     25358  4.8 20.3 6786856 6659356 pts/1 S    22:50   0:04 perl -E undef $/; open my $fh,"<", "tmp" or die; my $d = <$fh>; say "io done"; sleep 100000;
```

**Comment by benkasminbullock** [comment] 2017-07-18 21:18
It's not really a good idea to try to diagnose a problem with the use of a
library without looking at the documentation for the library.

**Comment by benkasminbullock** [comment] 2017-07-18 21:31
Please refer to

http://zlib.net/zlib_how.html

and

http://zlib.net/zpipe.c

The usage of zlib is not the problem here.

**Comment by ufobat** [comment] 2017-07-18 21:33
That's true. I didn't troubleshoot it. I just tried to point out a way to reproduce what caused an error in your module. It is up to you how you handle a bug report.

**Comment by benkasminbullock** [comment] 2017-07-18 23:36
On 19 July 2017 at 00:08, Martin Barth <notifications@github.com> wrote:

> I've encounering following error
>
> perl -MGzip::Faster=gunzip_file -we 'gunzip_file(shift);' 'test.bin.gz'
> Zlib did not come to the end of the string - -5 at /opt/perl/lib/site_perl/5.20.3/x86_64-linux/Gzip/Faster.pm line 76.
>
>
> in oder to figure out what zlib_status is i applyed follwing chagne:
>
> -- a/gzip-faster-perl.c
> +++ b/gzip-faster-perl.c
> @@ -373,7 +373,7 @@ gunzip_faster (gzip_faster_t * gf)
>         croak ("Zlib did not finish processing the string");
>      }
>      if (zlib_status != Z_STREAM_END) {
> -   croak ("Zlib did not come to the end of the string");
> +            croak ("Zlib did not come to the end of the string - %d", zlib_status);
>      }
>      inflateEnd (& gf->strm);
>      if (gf->user_object && gf->is_gzip && header.done == 1) {
>
> my file is rather big:
>
> $ dd if=/dev/urandom of=test.bin bs=100M count=50
> $ gzip test.bin
> $ ls -l test.bin.gz
> -rw-r--r-- 1 root root 5138896180 <(513)%20889-6180> 18. Jul 16:15
> test.bin.gz
>

I tried to reproduce this bug:

[ben@mikan] {08:09 45} ~ 500 $ dd if=/dev/urandom of=test.bin bs=100M
count=50
50+0 records in
50+0 records out
5242880000 bytes transferred in 142.796737 secs (36715685 bytes/sec)
[ben@mikan] {08:12 31} ~ 501 $ gzip test.bin
[ben@mikan] {08:16 50} ~ 502 $ ls -l test.bin.gz
-rw-r--r--  1 ben  ben  5244479317 Jul 19 08:12 test.bin.gz
[ben@mikan] {08:17 01} ~ 503 $ perl -MGzip::Faster=gunzip_file -we
'gunzip_file(shift);' 'test.bin.gz'
Out of memory!
[ben@mikan] {08:17 39} ~ 504 $

In my case I don't have enough memory to reproduce this bug but trigger the
error as seen above.


> i am wondering whether this is a memory issue? according to
> https://www.zlib.net/manual.html when you ancounter a Z_BUF_ERROR you
> should create you output buffer. which is not the case in the do while loopl
>

As I pointed out, but not very clearly, the while loop is not exited by the
Z_BUF_ERROR. The "break;" statement after Z_BUF_ERROR exits the switch()
statement, not the while loop. The while loop is only exited by either an
error condition which calls "croak"

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L347

etc.

 or by the final "while" condition here:

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L371

> If the parameter flush is set to Z_FINISH, pending input is processed,
pending output is flushed and  deflate returns with Z_STREAM_END if there
was enough output space. If deflate returns with Z_OK or Z_BUF_ERROR, this
function must be called again with Z_FINISH and more output space (updated
avail_out) but no more input data, until it returns with Z_STREAM_END or an
error. After deflate has returned Z_STREAM_END, the only possible
operations on the stream are deflateReset or deflateEnd.

In this case we are dealing with inflate, not deflate, but if Z_BUF_ERROR
is returned then the switch statement is exited, and the do / while loop
continues to execute, and the function is always called with Z_FINISH:

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L338

so the call to inflate is absolutely exactly what the manual says to do
here, as far as I can see.


The final condition of the statement

https://metacpan.org/source/BKB/Gzip-Faster-0.20/gzip-faster-perl.c#L371

is taken from the two zlib examples which I showed before.

https://github.com/benkasminbullock/gzip-faster/issues/7#issuecomment-316204093

However, at this point I notice that the zpipe example code checks for the
out condition and then checks for the error condition, and Z_BUF_ERROR
could fall through the inner do while loop and then fall to the outer loop.
It's possible that inflate needs to be called again or something, although
I'm not sure why it would need to overwrite the input data buffer like that.

I'll respond again when I have some more information.

**Comment by benkasminbullock** [comment] 2017-07-19 01:19
I've sent an email to the zlib developers regarding this bug since I was unable to reproduce it. I tried to CC the email to the following person:

https://metacpan.org/author/UFOBAT

However, that email seems not to be valid, since I got a rejected email message from gmail. If you want a copy, please let me know.

**Comment by benkasminbullock** [comment] 2017-07-20 01:52
Since I cannot see an error in the code, I did not receive a response from zlib and I cannot reproduce the bug, I'm labelling this as stalled. The only way forward I can suggest is if you can offer me an account on your machine where these files live and I can try to debug it over ssh.

**Comment by benkasminbullock** [comment] 2018-10-24 03:38
Closing this issue due to lack of further response.

**Closed by benkasminbullock** 2018-10-24 03:38 UTC
Labels: stalled
